@startuml

User -> AnimalShelterApp : requests to see all animals sorted by NAME
AnimalShelterApp -> AnimalService : printAllAnimals()
alt At least one animal in the shelter
AnimalService -> AnimalRepository : getAnimals()
AnimalService <- AnimalRepository : List<Animal>
AnimalShelterApp <-- AnimalService : sortAnimals(SortType name)
AnimalShelterApp <-- AnimalService : printEachAnimal(List<Animal> list)
User <-- AnimalShelterApp : show result
else No animal in the shelter
AnimalService <- AnimalRepository : return null
AnimalShelterApp <-- AnimalService : NoAnimalFoundException
User <-- AnimalShelterApp : error msg: no animal in the shelter
end

@enduml
