@startuml

User -> AnimalShelterApp : requests to see all animals
AnimalShelterApp -> AnimalService : returnAllAnimals()
alt At least one animal in the shelter
AnimalService -> AnimalRepository : getAnimals()
AnimalService <- AnimalRepository : List<Animal>
AnimalShelterApp <-- AnimalService : void()
User <-- AnimalShelterApp : show all animals found in the shelter
else No animal in the shelter
AnimalService <- AnimalRepository : return empty list
AnimalShelterApp <-- AnimalService : NoAnimalFoundException
User <-- AnimalShelterApp : error msg: no animal in the shelter
end

@enduml
