@startuml

User -> AnimalShelterApp : inputs NAME
AnimalShelterApp -> AnimalService : findAllAnimalsByName(String name)
AnimalService -> AnimalRepository : getAllAnimalsByName(String name)
alt At least one animal in the shelter
AnimalService <- AnimalRepository : List<Animal>
AnimalShelterApp <-- AnimalService : void()
User <-- AnimalShelterApp : show all animals found with that name
else No animal in the shelter
AnimalService <- AnimalRepository : return empty list
AnimalShelterApp <-- AnimalService : NoAnimalFoundException
User <-- AnimalShelterApp : error msg: no animal found with that name
end

@enduml
